"""initialize_database

Revision ID: c5e36cdeefe7
Revises:
Create Date: 2026-09-12 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

import Augment_Affil.models as models

# revision identifiers, used by Alembic.
revision = "c5e36cdeefe7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.create_table(
        "affil_inst",
        sa.Column("inst_key", sa.Integer(), nullable=False),
        sa.Column("inst_id", sa.String(), nullable=False),
        sa.Column("inst_parents", sa.String(), nullable=True),
        sa.Column("inst_canonical", sa.String(), nullable=False),
        sa.Column("inst_abbreviation", sa.String(), nullable=False),
        sa.Column("inst_country", sa.String(), nullable=True),
        sa.Column("inst_iso_country", sa.String(), nullable=True),
        sa.Column("inst_location", sa.String(), nullable=True),
        sa.Column("inst_rorid", sa.String(), nullable=True),
        sa.Column("inst_notes", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("inst_key"),
        sa.UniqueConstraint("inst_key"),
    )

    op.create_table(
        "affil_data",
        sa.Column("data_key", sa.Integer(), nullable=False),
        sa.Column("affil_id", sa.String(), nullable=False),
        sa.Column("affil_string", sa.Text(), nullable=False),
        sa.Column("norm_string", sa.Text(), nullable=False),
        sa.Column("flagged_multi", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("data_key"),
        sa.UniqueConstraint("data_key"),
        sa.UniqueConstraint("affil_string"),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grpc_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_hash", sa.String(), nullable=True),
        sa.Column("job_request", sa.String(), nullable=True),
        sa.Column("status", sa.Enum(models.Status), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("affil_inst")
    op.drop_table("affil_data")
    op.drop_table("grpc_status")
    op.execute("DROP TYPE Source")
    op.execute("DROP TYPE Status")

    # ### end Alembic commands ###
